//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPE3
{
    using System;
    using System.Collections.Generic;
    
    public partial class chauffeur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public chauffeur()
        {
            this.utilisation = new HashSet<utilisation>();
        }
    
        public int id { get; set; }
        public Nullable<int> le_chauffeur_id { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string statut { get; set; }
        public string adresse { get; set; }
        public string telephone_c { get; set; }
    
        public virtual entreprise entreprise { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<utilisation> utilisation { get; set; }
    }
}
