//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPE3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tregortransportEntities : DbContext
    {
        public tregortransportEntities()
            : base("name=tregortransportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<arret> arret { get; set; }
        public virtual DbSet<bus> bus { get; set; }
        public virtual DbSet<chauffeur> chauffeur { get; set; }
        public virtual DbSet<date> date { get; set; }
        public virtual DbSet<entreprise> entreprise { get; set; }
        public virtual DbSet<forfait> forfait { get; set; }
        public virtual DbSet<ligne> ligne { get; set; }
        public virtual DbSet<migration_versions> migration_versions { get; set; }
        public virtual DbSet<mode_payement> mode_payement { get; set; }
        public virtual DbSet<p> p { get; set; }
        public virtual DbSet<payement> payement { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<utilisation> utilisation { get; set; }
    }
}
