//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPE3
{
    using System;
    using System.Collections.Generic;
    
    public partial class payement
    {
        public int id { get; set; }
        public Nullable<int> les_utilisateurs_id { get; set; }
        public System.DateTime date_payement { get; set; }
        public Nullable<int> les_modes_payements_id { get; set; }
        public Nullable<int> le_forfait_id { get; set; }
        public Nullable<int> mode_payement_id { get; set; }
    
        public virtual forfait forfait { get; set; }
        public virtual user user { get; set; }
    }
}
